# This is a basic workflow to help you get started with Actions

name: Web.app CI

on:
  push:
    branches: 
      - '*'
    paths:
      - 'web.app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'web.app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web.app
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build --if-present
